### ISSUE TITLE
More broken links to fix

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Docs#10]
I just noticed some more broken links (since we moved the documentation to Redoc):

(Side note: _I just created that issue to collect the broken ones first, so I (or someone else) can correct them in one commit instead of several ones_)

- `installing-and-updating-2-deployment-options`
  - "Managed Deployments"
  - "Docker Deployments"
- `installing-and-updating-2-deployment-options-digital-ocean`
  - "Ubuntu"
  - "CentOS" 
  - "Deploy Rocket.Chat on Linux with Docker" 
- `installing-and-updating-3-using-docker-docker-nginx-ssl-hubot`
  - Any of the "What we’ll cover in this guide" links
- `installing-and-updating-3-using-docker-docker-compose`
  - "Docker Images Available"
- `installing-and-updating-3-using-docker-docker-images-available`
  - "current branching strategy"
- `user-guides`
- `user-guides-file-uploads`
- `server-management-administration-settings`
- `server-management-pm2-systemd-upstart`
  - "this guide"

**Comment by engelgabriel** [comment]
Hi @frdmn, I have invited you to our documentation team.

**Comment by gmsecrieru** [comment]
From digging into Redoc's source code, I think that our main problem here is the structure of `Rocket.Chat.Docs` articles. Redoc identifies folders (and uses this logic for rendering menu levels and URLs accordingly) based on the presence of `README.md` on the current item path. 

I _think_ (and not _guarantee_ as I lack a proper test environment :D) we may be better of with the following convention:
```
- 1. How can I help?
	- Contributing
	 ` README.md
	- Promoting
	 ` README.md
	- Reporting Security Issues
	 ` README.md
```

**Comment by engelgabriel** [comment]
The advantage of this structure would be to be able to put inside each folder, all the media assets need on that page, and reference them just by name, so they will work anywhere.

**Comment by lkraider** [comment]
https://rocket.chat/docs/master/installing-and-updating-2-deployment-options-ubuntu
![screen shot 2016-04-15 at 22 04 02](https://cloud.githubusercontent.com/assets/52256/14578125/035c7a80-0356-11e6-9f89-8f3613eb0de7.png)

**Comment by frdmn** [comment]
Interesting. Can someone shed some light in here (/cc @RocketChat/documentation-and-wiki)? Seems that there are no latest GitHub commits that could break the whole docs system like that.

**Comment by gmsecrieru** [comment]
I will try to setup an environment and repo doc following the structure I mentioned for testing. Hopefully it will be a matter of following that convention :)

**Comment by gmsecrieru** [comment]
I'll take that back. I've forked the repo and (applied the suggested structure)[https://github.com/gmsecrieru/Rocket.Chat.Docs/commit/75833d894cd26628634c25983517ba8b244864ec] but that does not address the issue without code changes. I will keep looking into it! :)

/cc @marceloschmidt

**Comment by gmsecrieru** [comment]
Please follow up on [https://github.com/RocketChat/redoc/pull/3]

**Comment by frdmn** [comment]
Since this is now fixed, I'll rewrite the links tomorrow back into the original state.

**Comment by lkraider** [comment]
This relative link is broken:
![screen shot 2016-04-18 at 22 16 35](https://cloud.githubusercontent.com/assets/52256/14624709/7fb14aa2-05b3-11e6-9924-6dfd7da9116d.png)
