### ISSUE TITLE
Link anchors doesn't work in Redoc

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.Docs#19]
I tried fixing a link anchor in the Ubuntu guide:

```diff
-1. Repeat Installation [step](#2-install-rocketchat)
+1. Repeat Installation [step](Ubuntu.md#2-install-rocketchat)
```

Because the original state ended up in an `invalid` link as @lkraider reported (https://github.com/RocketChat/Rocket.Chat.Docs/issues/10#issuecomment-211669533), I tried this but failed because it doesn't get correctly processed by Redoc.

The link turns into `https://rocket.chat/docs/master/installing-and-updating/deployment-options/Ubuntu.md#2-install-rocketchat` but because of the `.md` it links to a new (non existent) article.

Any ideas @RocketChat/documentation-and-wiki?

**Comment by gmsecrieru** [comment]
@frdmn could you please you confirm this is still an issue after latest changes on MD-to-HTML link replacements?

**Comment by gmsecrieru** [comment]
On a side note, I believe we should stick with whatever works perfectly on GitHub and adapt our Redoc for should the need arise. Aye? 

/cc @engelgabriel

**Comment by frdmn** [comment]
@gmsecrieru Yes, it's still broken. It now renders as:

```
http://localhost:3000/master/installing-and-updating/manual-instalation/ubuntu/ubuntu-md-2-install-rocketchat
```

**Comment by engelgabriel** [comment]
I agree with @gmsecrieru 

The objective is to keep it 100% compatible with GitHub, so we fix Redoc to be compatible when needed.

**Comment by gmsecrieru** [comment]
Since we are moving to a directory-oriented structure, that URL was not valid anymore. For any further changes: 

- When referencing the same file, you should use `Repeat Installation [step](#2-install-rocketchat)`
- When referencing other files, you should use `/3.%20Installing%20and%20Updating/4.%20Manual%20Instalation/FreeBSD#packages`

That will work for GitHub and should work for our Redoc fork too -- otherwise I will jump in and fix it.

Keep up the great work!

**Comment by engelgabriel** [comment]
@gmsecrieru any chance we can make the regex for URL work with SPACES and not just %20 ?

**Comment by gmsecrieru** [comment]
@engelgabriel seems like `markdown-it` does not even parse these strings as actual URLs so we can't  replace them, e.g.:
![markdown-it-decoded](https://cloud.githubusercontent.com/assets/190883/14955296/66a83614-104f-11e6-99df-b22cd7056780.gif)

We might be able to use different package(s) and adapt our fork to use it, but I wonder if that's worth the trouble. 

Pinging Markdown SME @geekgonecrazy for thoughts :)

**Comment by geekgonecrazy** [comment]
Do we know of any markdown editor anywhere that handles spaces in links?  I don't know of any that do.  This is I think just one of those HTML link encoding things... We might be able to hack something in that would recognize links and replace spaces with `%20` before passed to the markdown engine?

But should we?
