### ISSUE TITLE
Suggested theme with jekyll.

### ISSUE THREAD

**Issue by lobocode** [RocketChat/Rocket.Chat.Docs#20]
How about adapting the theme of documentation for this http://idratherbewriting.com/documentation-theme-jekyll/ ?

Source-code with jekyll : https://github.com/tomjohnson1492/documentation-theme-jekyll 

Particularly, I enjoyed. I volunteer to help with this if you agree.

**Comment by engelgabriel** [comment]
Unfortunately Jekyll is Ruby, and we are NodeJS experts... so we try to keep things on the Javascript world. Ideally Redoc would become the Jekyll of NodeJS.

**Comment by engelgabriel** [comment]
I was wondering what Ghost uses for http://support.ghost.org/getting-started/

Anyone?

**Comment by frdmn** [comment]
@engelgabriel According to the source code, it looks like an modified WordPress theme:

```
<script type='text/javascript' src='//support.ghost.org/wp-content/themes/knowhow-childtheme/anchor.min.js?ver=20140807'></script>
<script type='text/javascript' src='//support.ghost.org/wp-content/themes/knowhow-childtheme/main.js?ver=20140807'></script>
<script type='text/javascript' src='//support.ghost.org/wp-content/themes/knowhow/js/functions.js?ver=4.5'></script>
<script type='text/javascript' src='//support.ghost.org/wp-content/themes/knowhow/framework/shortcodes/shortcodes.js?ver=4.5'></script>
<script type='text/javascript' src='//support.ghost.org/wp-includes/js/wp-embed.min.js?ver=4.5'></script>
<script type='text/javascript' src='//support.ghost.org/wp-content/themes/knowhow/js/jquery.livesearch.js?ver=4.5'></script>
```
