### ISSUE TITLE
editorconfig link not found

### ISSUE THREAD

**Issue by SangyulCha** [RocketChat/Rocket.Chat.Docs#2031]
editorconfig link in docs/contributors/contributor-guidlines.md does not exist. (https://github.com/RocketChat/handbook/tree/d83129860783e026ac41ca3c8cf8cf0f4b3dd1f2/product/.editorconfig/README.md)

**Comment by Rodriq** [comment]
This section moved to the developer's docs, https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat/code-style-guide with all the links working.

`.editorconfig` [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/.editorconfig)
