### ISSUE TITLE
Broken link on curl command - Docker & Docker Compose page

### ISSUE THREAD

**Issue by Plorenzo** [RocketChat/Rocket.Chat.Docs#2033]
If you try to run the recommended command to get the example docker file from rocket chat you get the homepage HTML instead. 

`curl -L https://go.rocket.chat/i/docker-compose.yml -O`

because the link `https://go.rocket.chat/i/docker-compose.yml ` is broken, basically redirects to https://rocket.chat

File to change here: https://github.com/RocketChat/docs/tree/master/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose

**Comment by Rodriq** [comment]
This has been updated to `curl -L https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml -O`
as seen here https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose
Thanks
