### ISSUE TITLE
docker-compose.yml in tutorial not linked correctly

### ISSUE THREAD

**Issue by arunoruto** [RocketChat/Rocket.Chat.Docs#2035]
I noticed the `docker-compose.yml` file in [this](https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose) tutorial isn't correctly linked and gives a `404` error. It seems like it needs to be updated to point to https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/docker-compose.yml

**Comment by Rodriq** [comment]
Updated. Thanks :)
