### ISSUE TITLE
Outgoing Webhook Script seems to have changed

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.Docs#2036]
With my old script I'm unable to use the server response.
While `return response;` leads to an empty message I've tried `return response.content;` which worked.
So `process_outgoing_response` only expects an array with `{"text":"",...}` and not an additional `{content:{"text":"",...}}` layer.
Currently using RC 4.6.0 - don't know when this exactly stopped working in that way.

**Comment by dudanogueira** [comment]
Hi!

Here is the doc for the outgoing webhook script:
https://docs.rocket.chat/guides/administration/admin-panel/integrations#script-details-1

You have two functions:

**prepare_outgoing_request**: This will change the outgoing payload or can return a message.

**process_outgoing_response**: This will react according to the response and can be used to parse the response.

Here you have a script I have based on the example in docs that may help you:
https://gist.github.com/dudanogueira/ae8e92c5071b750de405546980eba7dc

The documentation is working, and I can't confirm there was a change on how it used to work.

Please, consider using our [Community Support Channel](https://open.rocket.chat/channel/support) if you need some assistance on that.
