### ISSUE TITLE
获取图片时显示重载且文件也无法下载，请各位大神帮忙解决一下，或者你们有没有遇到过此问题？

### ISSUE THREAD

**Issue by l1172023402** [RocketChat/Rocket.Chat.Docs#2038]
图片就显示如此，服务器内存时够的，而且其他人也都好使，只有两个账号是这种情况
![Clipboard - 2022年5月13日上午10点03分](https://user-images.githubusercontent.com/105470277/168196770-5a4d4627-208c-40dd-b19a-554cfdffe306.png)
![Clipboard - 2022年5月13日上午10点04分](https://user-images.githubusercontent.com/105470277/168196841-7671ca3f-de93-48fa-a3bd-9da238fc1326.png)

**Comment by dudanogueira** [comment]
Hi!

I have translated, and from the pictures, my bet is that you need to register the domain at Admin > Omnichannel > Livechat > Livechat allowed Domains.

I will close this issue, please use our [Community Support Channel](https://open.rocket.chat/channel/support) or [Forums](http://forums.rocket.chat) for support.
