### ISSUE TITLE
broken links in iframe docs

### ISSUE THREAD

**Issue by sagarghanshyamdigital** [RocketChat/Rocket.Chat.Docs#2039]
The following docs have broken references in all links. 

https://github.com/RocketChat/docs/blob/master/guides/administration/misc.-admin-guides/authentication/README.md

https://github.com/RocketChat/docs/blob/master/guides/administration/misc.-admin-guides/authentication/single-sign-on-iframe.md

**Comment by Rodriq** [comment]
Thanks for pointing this out. The links have been updated.
https://docs.rocket.chat/guides/administration/advanced-admin-settings/authentication
https://docs.rocket.chat/guides/administration/advanced-admin-settings/authentication/single-sign-on-iframe
