### ISSUE TITLE
"Security fixes and updates" documentation page not updated anymore

### ISSUE THREAD

**Issue by amottier** [RocketChat/Rocket.Chat.Docs#2042]
Latest security issue listed on ["Security fixes and updates" documentation page](https://docs.rocket.chat/guides/security/security-updates) was on 2021-07-13, but security release such as [version 4.3.3](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.3.3) published on 2022-01-28 are not listed in the documentation page.

**Comment by Faria1212** [comment]
Doc updated. Thank you.
