### ISSUE TITLE
Broken Link in Integrations Page

### ISSUE THREAD

**Issue by J12934** [RocketChat/Rocket.Chat.Docs#2045]
Hi 👋

The "integrations" page ([website](https://docs.rocket.chat/guides/administration/admin-panel/integrations), [on github](https://github.com/RocketChat/docs/tree/master/guides/administration/admin-panel/integrations)) has a broken link [“Post a chat message”](https://github.com/RocketChat/docs/blob/master/guides/administration/admin-panel/integrations/broken-reference).

Would love if this could be fixed, I really wanted to have a look at the that link, and am currently lost in finding where it would have pointed to 😅

**Comment by Faria1212** [comment]
It was fixed. Thank you
