### ISSUE TITLE
Missing documentation for Call Center VoIP integration with Asterisk

### ISSUE THREAD

**Issue by davidbqzt** [RocketChat/Rocket.Chat.Docs#2059]
### Description:
I've just configured the Rocket.Chat Call Center integration with an Asterisk Server, it's being a hard work of reading logs and console messages, and finding out what was missing or what was required, because the documentation is short and missing, and the forums have not too much information about it.
I read:

- https://docs.rocket.chat/guides/rocket.chat-call-center/voip-introduction/voip-prerequisites
- https://docs.rocket.chat/guides/rocket.chat-call-center/call-center-admin-guides
- https://docs.rocket.chat/guides/rocket.chat-call-center/call-center-admin-guides/how-to-configure-voip-on-my-rocket.chat-instance
- https://docs.rocket.chat/guides/rocket.chat-call-center/call-center-admin-guides/how-to-associate-agents-with-extensions
- https://docs.rocket.chat/guides/rocket.chat-call-center/call-center-admin-guides/voip-troubleshooting (completely blank)

and found out that there was too much information missing. I would like to add all I learned to that documentation.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: SaaS
- Deployment Method: SaaS
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.8

**Comment by dudanogueira** [comment]
Hi! Thanks for your interest in helping. 

I will move this issue to our docs repo

**Comment by dudanogueira** [comment]
Please, feel free to reach me at our open server so we can arrange the best way for you to contribute to our docs regarding VOIP:

https://open.rocket.chat/direct/duda.nogueira

Your input on this is very much appreciated. I am about to start some efforts integrating it with FreePBX and Issabel, some popular open source PABX based in Asterisk

**Comment by Faria1212** [comment]
We are working on it. Please check our docs in a few days.
