### ISSUE TITLE
how-can-i-help is not working

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Docs#2079]
This page "https://github.com/RocketChat/docs/blob/master/contributors/how-can-i-help/broken-reference/README.md" is not working.

**Comment by dudanogueira** [comment]
Hi!

Where did you find the link for it? We have been moving some docs around

Thanks for pointing it out!

**Comment by ghost** [comment]
https://docs.rocket.chat/contributors/how-can-i-help/reporting-issues

![image](https://user-images.githubusercontent.com/28378264/187750086-4cca888d-b42b-4968-9a03-2dd4535b85dd.png)

"Getting Suport"

**Comment by Faria1212** [comment]
@rayamfonseca  Here is the new link https://docs.rocket.chat/getting-support/community-resources We've added a redirect as well. Hope it will start to work soon.
