### ISSUE TITLE
Bug Report : Link Broken at Developing page of Rocket.chat Docs

### ISSUE THREAD

**Issue by SiddheshKukade** [RocketChat/Rocket.Chat.Docs#2081]
Steps to Reproduce ⬇️ 
1. Go to `https://docs.rocket.chat/contributors/how-can-i-help/developing`
2. Scroll until you see this 
![image](https://user-images.githubusercontent.com/65951872/191333866-53cf41cf-70cd-42cf-a392-82f9deaac015.png)
3. Click on the `Rocket Chat Environment Setup` Button
4. It takes to a page with 404 error `https://developer.rocket.chat/rocket.chat/rocket.chat-server` 
![image](https://user-images.githubusercontent.com/65951872/191334017-706dc16d-d05a-4861-9b5d-7f39da423b84.png)

Solution ⬇️ 
Can be resolved by providing the correct link for development setup page

**Comment by Faria1212** [comment]
Issue resolved. Thank you for your contribution.
