### ISSUE TITLE
Introduction/prerequisites link showing 404 error in Docs

### ISSUE THREAD

**Issue by ayushbhaimehta** [RocketChat/Rocket.Chat.Docs#2091]
https://developer.rocket.chat/quick-start/choosing-a-development-host
In this when you click on Introduction/prerequisites
![bfr](https://user-images.githubusercontent.com/77238801/212942266-6d4e43fd-13df-4c0b-b5f0-78dfa8fee92b.png)

It shows a 404 error
![err](https://user-images.githubusercontent.com/77238801/212942311-f4d1c008-556b-41b0-8517-372017d2a593.png)

**Comment by Faria1212** [comment]
We have updated the link. Thank you for reporting this.

**Comment by ayushbhaimehta** [comment]
You need to change it from here 
![image](https://user-images.githubusercontent.com/77238801/212949888-fff75df0-1f54-4323-b442-ca4d38485431.png)
Clicking on official recommendations is still not linked to anything

**Comment by Faria1212** [comment]
Fixed that too. 👍
