### ISSUE TITLE
community Icon isn't visible.

### ISSUE THREAD

**Issue by Pheewww** [RocketChat/Rocket.Chat.Docs#2097]
![icon issue](https://user-images.githubusercontent.com/67512605/221353560-d38e3f28-9844-44ea-a579-f2545a2c493a.png)

when i tried to open the icon in new tab, it says "The access to the resource has been denied".

**Comment by Faria1212** [comment]
Can you share the link of the page

**Comment by Pheewww** [comment]
https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat  

pls scroll down to To join other contributors section.

**Comment by Faria1212** [comment]
We fixed it. Here is the link https://forums.rocket.chat/ just in case
