### ISSUE TITLE
Create-space Link needs to be updated.

### ISSUE THREAD

**Issue by Pheewww** [RocketChat/Rocket.Chat.Docs#2099]
![create_space](https://user-images.githubusercontent.com/67512605/221354269-1462f96c-132e-4813-b873-c491750c8bb6.png)

on clinking, page not found is shown on gitbook website.

**Comment by Faria1212** [comment]
Please share the link of this page

**Comment by Rodriq** [comment]
Docs updated https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help/documentation#using-gitbook
