### ISSUE TITLE
responsive navbar

### ISSUE THREAD

**Issue by Ni-011** [RocketChat/Rocket.Chat.Docs#2101]
![image](https://user-images.githubusercontent.com/63962929/222800345-b28f0b6a-f611-4ccb-8298-0e04cadfba08.png)

the links on navbar flows their characters to next line when shrunk, it could be better if they just got smaller in size and not flow to next line to maintain readability

**Comment by kowais915** [comment]
I would love to fix this, but I could not find any instructions on rebuilding this site on my local machine.

**Comment by Rodriq** [comment]
Thank you @NitinRana01125532553 
Rocket.Chat uses Gitbook to manage documentation. This is handled by them.
I suggest you scale to real device width. It's responsive enough.
If you have any other issues, please feel free to open a new issue. I'll be closing this.

CC: @kowais915 

Thanks!
